# Nombre del flujo de trabajo
name: Despliegue al Servidor

# Disparador para las ramas main y develop
on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Este paso clona tu repositorio en la máquina virtual de GitHub
      # para que el script deploy.sh esté disponible.
      - name: Clonar repositorio
        uses: actions/checkout@v3

      # Este paso se conecta a tu servidor y ejecuta el script inteligente
      - name: Desplegar en el servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            # Le pasamos las variables necesarias al script que se ejecutará
            export DEPLOY_BRANCH=${{ github.ref_name }}
            export SUDO_PASSWORD='${{ secrets.SUDO_PASSWORD }}'
            
            # Navegamos a la carpeta del repositorio en el servidor
            cd /home/linuxuser/visor-monitoreo-regional
            
            # Nos aseguramos de tener la última versión del script de despliegue
            git pull origin $DEPLOY_BRANCH

            # Ejecutamos el script de despliegue
            sh ./deploy.sh