name: Despliegue de Visor Monitoreo Regional

on:
  push:
    branches:
      - main
      - develop

# Tareas a ejecutar
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio en la máquina virtual de GitHub Actions      
      - name: Checkout del código
        uses: actions/checkout@v3 # Usa la versión más reciente si es compatible (v4 o superior)

      # Paso 2: Conectarse a servidor y ejecutar el script deploy.sh
      - name: Desplegar en el servidor remoto
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}          
          script: |
            # Navegar al directorio donde se encuentra el script deploy.sh
            # Asumo que deploy.sh está en /home/linuxuser/
            # Si deploy.sh está dentro de visor-monitoreo-regional, ajusta la ruta
            cd /home/linuxuser/

            # Dar permisos de ejecución al script deploy.sh si no los tiene ya
            # Es buena práctica asegurar esto en el flujo de CI/CD
            chmod +x deploy.sh

            # Ejecutar el script deploy.sh, pasándole la rama actual como variable de entorno
            # La variable DEPLOY_BRANCH se define aquí y es utilizada por deploy.sh
            # ${{ github.ref_name }} obtendrá el nombre de la rama (ej. 'main' o 'develop')
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S DEPLOY_BRANCH="${{ github.ref_name }}" ./deploy.sh

            echo "--- Flujo de despliegue completado para la rama ${{ github.ref_name }} ---"

