# Nombre del flujo de trabajo
name: Despliegue al Servidor

# Disparador para las ramas main y develop
on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Este paso clona tu repositorio en la máquina virtual de GitHub
      # para que el script deploy.sh esté disponible.
      - name: Clonar repositorio
        uses: actions/checkout@v3

      # Este paso se conecta a tu servidor y ejecuta el script inteligente
      - name: Desplegar en el servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo "--- INICIANDO DEPURACIÓN EN EL SERVIDOR ---"

            echo ">>> 1. Listando archivos y permisos en la carpeta de PRODUCCIÓN:"
            ls -la /home/linuxuser/visor-monitoreo-regional

            echo ">>> 2. Mostrando contenido de deploy.sh en la carpeta de PRODUCCIÓN:"
            cat /home/linuxuser/visor-monitoreo-regional/deploy.sh

            echo ">>> 3. Listando archivos y permisos en la carpeta de STAGING:"
            ls -la /home/linuxuser/senapred-monitor-staging

            echo ">>> 4. Mostrando contenido de deploy.sh en la carpeta de STAGING:"
            cat /home/linuxuser/senapred-monitor-staging/deploy.sh

            echo "--- FIN DE LA DEPURACIÓN ---"